version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/grt-web-b2b
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13

      # Docker login
      - run:
          name: Docker login
          command: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

      # Restore cache
      - restore_cache:
          key: grt-{{ .Branch }}-{{ checksum "package.json" }}

      # Install
      - run: npm ci

      # Store cache
      - save_cache:
          key: grt-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"

      # Run tests
      #- run: xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
      #- run: xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js

      - deploy:
          name: Docker image build
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              TAG="latest-dev"
              BUILD_ENV="staging"
            else
              TAG="latest-prod"
              BUILD_ENV="production"
            fi

            if [ "$CIRCLE_BRANCH" == "master" ] || [ "$CIRCLE_BRANCH" == "production" ]; then
              docker build --build-arg="BUILD_ENV=$BUILD_ENV" -t gre-web-b2b -f Dockerfile .
              docker tag gre-web-b2b gorealeurope/gre-web-b2b:$TAG
              docker tag gre-web-b2b gorealeurope/gre-web-b2b:build-$CIRCLE_BUILD_NUM
              docker push gorealeurope/gre-web-b2b
            fi

